import pygame


def load_texture(file_name):
    return pygame.image.load(f"{TEXTURE_PATH}\\{file_name}.{TEXTURE_FILE_EXT}")


WIDTH = "w"  # Yes I'm funny
HEIGHT = "h"

# SCREEN_SIZE = {WIDTH: 1609, HEIGHT: 909}
SCREEN_SIZE = {WIDTH: 1366, HEIGHT: 704}

DIRECTION_NORTH = "n"
DIRECTION_NORTHWEST = "nw"
DIRECTION_NORTHEAST = "ne"
DIRECTION_EAST = "e"
DIRECTION_SOUTH = "s"
DIRECTION_SOUTHWEST = "sw"
DIRECTION_SOUTHEAST = "se"
DIRECTION_WEST = "w"

DIRECTION_ORDER = (DIRECTION_NORTH, DIRECTION_NORTHEAST, DIRECTION_EAST, DIRECTION_SOUTHEAST,
                   DIRECTION_SOUTH, DIRECTION_SOUTHWEST, DIRECTION_WEST, DIRECTION_NORTHWEST)

TEXTURE_PATH = "images"
SOUND_PATH = "sounds"
TEXTURE_FILE_EXT = "png"
SOUND_FILE_EXT = "mp3"

TEXTURE_BACKGROUND_NAME = "background"
TEXTURE_SLIME_NAME = "slime"
TEXTURE_GOLDEN_SLIME_NAME = "golden_slime"
TEXTURE_SPEED_MUSH_NAME = "speed_mush"

TEXTURE_DIAG_SIZE = {WIDTH: 60, HEIGHT: 60}  # Diagonal textures size (nw ne sw se)
TEXTURE_PERP_VERT_SIZE = {WIDTH: 24, HEIGHT: 80}  # Perpendicular textures size (n s)
TEXTURE_PERP_HORZ_SIZE = {WIDTH: 80, HEIGHT: 24}  # Perpendicular textures size (e w)

TEXTURE_NORTH = load_texture(DIRECTION_NORTH)
TEXTURE_NORTHWEST = load_texture(DIRECTION_NORTHWEST)
TEXTURE_NORTHEAST = load_texture(DIRECTION_NORTHEAST)
TEXTURE_EAST = load_texture(DIRECTION_EAST)
TEXTURE_SOUTH = load_texture(DIRECTION_SOUTH)
TEXTURE_SOUTHWEST = load_texture(DIRECTION_SOUTHWEST)
TEXTURE_SOUTHEAST = load_texture(DIRECTION_SOUTHEAST)
TEXTURE_WEST = load_texture(DIRECTION_WEST)
TEXTURE_BACKGROUND = load_texture(TEXTURE_BACKGROUND_NAME)

TEXTURE_SLIME = load_texture(TEXTURE_SLIME_NAME)
TEXTURE_GOLDEN_SLIME = load_texture(TEXTURE_GOLDEN_SLIME_NAME)
TEXTURE_SPEED_MUSH = load_texture(TEXTURE_SPEED_MUSH_NAME)

SOUND_TING_NAME = "ting"

DIRECTION_TEXTURE_MATCH = {DIRECTION_NORTH: TEXTURE_NORTH, DIRECTION_NORTHWEST: TEXTURE_NORTHWEST,
                           DIRECTION_NORTHEAST: TEXTURE_NORTHEAST, DIRECTION_EAST: TEXTURE_EAST,
                           DIRECTION_SOUTH: TEXTURE_SOUTH, DIRECTION_SOUTHWEST: TEXTURE_SOUTHWEST,
                           DIRECTION_SOUTHEAST: TEXTURE_SOUTHEAST, DIRECTION_WEST: TEXTURE_WEST}

MOVE_DIRECTION_MATCH = {(0, -1): DIRECTION_NORTH, (1, 0): DIRECTION_EAST,
                        (0, 1): DIRECTION_SOUTH, (-1, 0): DIRECTION_WEST,
                        (1, -1): DIRECTION_NORTHEAST, (1, 1): DIRECTION_SOUTHEAST,
                        (-1, -1): DIRECTION_NORTHWEST, (-1, 1): DIRECTION_SOUTHWEST}

EFFECT_SCORE_UP = "score_up_"
EFFECT_SPEED_UP = "speed_up_"
EFFECT_SPEED_MUSH_MULTIPLIER = 2

TYPE_EFFECT = {
    TEXTURE_SLIME_NAME: (f"{EFFECT_SCORE_UP}1", ),
    TEXTURE_GOLDEN_SLIME_NAME: (f"{EFFECT_SCORE_UP}10", ),
    TEXTURE_SPEED_MUSH_NAME: (f"{EFFECT_SPEED_UP}30@{EFFECT_SPEED_MUSH_MULTIPLIER}", ),
}

ANIMATION_DELAY = 5
TICK_RATE = 60
SWORD_SPEED = 7
DASH_MULTIPLIER = 3
DASH_DURATION = 0.25  # Seconds
DASH_COOLDOWN = 2
UNDASHABLE_DURATION = 0.5
SCREEN_PADDING = 50
